spring:
  datasource:
    url: jdbc:h2:mem:test;Mode=Oracle;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
#    hibernate:
#      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop